name: isolate_http
description: IsolateHttp provides a way to launch 'http' library in Isolate with IsolatesFlutter. 
version: 1.0.0
homepage: https://github.com/thongdn-it/isolate_flutter/tree/master/isolate_http
repository: https://github.com/thongdn-it/isolate_flutter/tree/master/isolate_http

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  isolate_flutter: ^1.0.0
  http: ^0.12.0
  http_parser: ">=0.0.1 <4.0.0"